### ISSUE TITLE
require future

### ISSUE THREAD

**Issue by GeopJr** [lbarasti/concur#1]
While testing this shard, I noticed that `future.cr` needs to be explicitly required (`require "./lib/concur/src/**"`) which is not mentioned on the readme (without explicitly requiring it, `Future` is not defined).

#### Example Solutions

- require future inside `concur.cr`
- rename `concur.cr` into `channel.cr`, move that and `future.cr` into a separate folder and create a new `concur.cr` that just requires them.

(Unless there's something wrong with my setup or explicitly requiring it is by design 😅)

**Comment by lbarasti** [comment]
Hey @GeopJr, thanks for raising this. You are right, the intention was for `Future` to be available as soon as one requires concur :+1: 
I've published `v1.0.2`, where the issue should be fixed - hopefully I haven't messed anything else up in terms of namespace :sweat_smile: 
Let me know if you notice anything else suspicious, and do feel free to open more issues, I'm really looking for some feedback on the usability of this shard :pray:

**Comment by GeopJr** [comment]
Thanks for the quick fix! 🙌

`Future#on_complete` (/success/error) is very useful so I'll probably end up using it on a few projects!
